mutation MetWithProtected(
  $userId: String!
  $protectedId: String!
  $metWith: String!
  $meetingBooked: String
  $comment: String
) {
  editProtectedName (
    userId: $userId
    protectedId: $protectedId
    meetingBooked: $meetingBooked
    metWith: $metWith
    comment: $comment
  ) {
    id
    name {
      id
      firstName
      lastName
      phone
      company {
        id
        name
        address
        phone
      }
    }
    callBooked
    meetingBooked
    metWith
    created_at
  }
}
