  mutation EditUserDetails (
    $id: String!
    $firstName: String
    $lastName: String
    $email: String
    $phone: String
  ) {
    editUser(
      id: $id
      firstName: $firstName
      lastName: $lastName
      email: $email
      phone: $phone
    ) {
      id
      firstName
      lastName
      email
      phone
      updated_at
    }
  }
