mutation BookMeeting(
  $userId: String!
  $protectedId: String!
  $meetingBooked: String!
){
  editProtectedName (
    userId: $userId
    protectedId: $protectedId
    meetingBooked: $meetingBooked
  ) {
    id
    meetingBooked
    name {
      id
      firstName
      lastName
    }
  }
}
