mutation EditName (
  $userId: String!
  $nameId: String!
  $firstName: String!
  $lastName: String!
  $phone: String!
) {
  editName (
    userId: $userId
    nameId: $nameId
    firstName: $firstName
    lastName: $lastName
    phone: $phone
  ) {
    id
    firstName
    lastName
    phone
  }
}
