mutation EditComment(
  $commentId: String!
  $userId: String!
  $text: String
  $visibility: VisibilityEnumType
) {
  editNameComment(
    commentId: $commentId
    userId: $userId
    text: $text
    visibility: $visibility
  ) {
    id
    subject
    text
    visibility
    created_at
    updated_at
    commentUser {
      id
      firstName
      lastName
    }
  }
}
