query GetNameComments($id: String!, $userId: String!) {
  name(id: $id, userId: $userId) {
    id
    comments {
      id
      subject
      text
      visibility
      created_at
      updated_at
      commentUser {
        id
        firstName
        lastName
      }
    }
  }
}

