version: 2.1
orbs:
  heroku: circleci/heroku@0.0.6
jobs:
  build:
    working_directory: ~/ClientRelationshipManagerUI
    docker:
      - image: circleci/node:10.15.3-browsers
    steps:
      - add_ssh_keys:
          fingerprints:
            - '1c:4c:23:f2:da:be:d5:1f:4f:3a:d5:4a:30:3b:0b:39'
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-{{ .Branch }}-
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      # Test
      - run:
          name: Run unit tests
          command: yarn test
      - run:
          name: Build against Staging
          command: yarn run build
          environment:
            REACT_APP_GRAPHQL_CONFIG: staging
      - run:
          name: Serve staging app on CI
          command: yarn serve
          background: true
      - run:
          name: Run Feature tests
          command: yarn run test:feature:staging
      - run:
          name: Run new Feature tests
          command: yarn run test:feature-new
          environment:
            CYPRESS_baseUrl: http://localhost:5000
            CYPRESS_password: Vv07919911824
      - run:
          name: Update HEROKU_APP_NAME based on branch name
          command: |
            if [[ "$CIRCLE_BRANCH" = "master" ]]; then
              echo 'export HEROKU_APP_NAME="regency-wealth-crm"' >> $BASH_ENV
            else
              echo 'export HEROKU_APP_NAME="regency-wealth-crm-staging"' >> $BASH_ENV
            fi
      - heroku/install
      - heroku/deploy-via-git:
          force: true
      - store_artifacts:
          path: output
