mutation CreateUser (
  $firstName: String!
  $lastName: String!
  $email: String!
  $phone: String!
  $password: String!
  $accountType: UserAccountTypeEnumType!
  $companyFields: CompanyInputType!
) {
  createUser(
    firstName: $firstName
    lastName: $lastName
    password: $password
    email: $email
    phone: $phone
    accountType: $accountType
    companyFields: $companyFields
) {
    id
    firstName
    lastName
    email
    phone
    created_at
  }
}
