mutation BookCall(
  $userId: String!
  $protectedId: String!
  $callBooked: String
  $comment: String
){
  editProtectedName (
    userId: $userId
    protectedId: $protectedId
    callBooked: $callBooked
    comment: $comment
  ) {
    id
    callBooked
    name {
      id
      firstName
      lastName
    }
  }
}
