  query GetUserProfile($id: String!) {
    user(id: $id) {
      id
      firstName
      lastName
      email
      phone
      updated_at
      company {
        id
        name
        address
        phone
        updated_at
      }
    }
  }
