mutation EditCompany (
  $userId: String!
  $companyId: String!
  $name: String!
  $address: String!
  $phone: String!
) {
  editCompany (
    userId: $userId
    companyId: $companyId
    name: $name
    address: $address
    phone: $phone
  ) {
    id
    name
    address
    phone
  }
}
