mutation CreateUnprotectedName(
  $userId: String!
  $firstName: String!
  $lastName: String!
  $phone: String!
  $companyFields: CompanyInputType!
) {
  addUnprotectedNameToUser(
    userId: $userId
    firstName: $firstName
    lastName: $lastName
    phone: $phone
    companyFields: $companyFields
  ) {
    id
    name {
      id
      firstName
      lastName
      phone
      created_at
      updated_at
      company {
        id
        name
        address
        phone
        created_at
        updated_at
      }
    }
    created_at
  }
}
